cleanup gcc errors
ex 1
nanodbc/nanodbc/nanodbc.cpp:1865:25: error: conversion from ‘int’ to ‘SQLUSMALLINT’ {aka ‘short unsigned int’} may change value [-Werror=conversion]

ex 2
nanodbc/nanodbc.cpp:4009:17: error: missing initializer for member ‘tm::tm_min’ [-Werror=missing-field-initializers]

command line
/usr/bin/g++ -DNDEBUG -Dnanodbc_EXPORTS -I/i/ports/repo/nanodbc -fnon-call-exceptions -Wall -Wnarrowing -Werror -O3 -DNDEBUG -fPIC -I/usr/include -DHAVE_UNISTD_H -DHAVE_PWD_H -DHAVE_SYS_TYPES_H -DHAVE_LONG_LONG -DSIZEOF_LONG_INT=8 -Wall -Wextra -Wconversion -Wno-error=implicit-fallthrough= -Wno-error=unused-parameter -Wno-error=float-conversion -std=c++20 -MD -MT CMakeFiles/nanodbc.dir/nanodbc/nanodbc.cpp.o -MF CMakeFiles/nanodbc.dir/nanodbc/nanodbc.cpp.o.d -o CMakeFiles/nanodbc.dir/nanodbc/nanodbc.cpp.o -c nanodbc/nanodbc/nanodbc.cpp