Do not declare async methods if NANODBC_DISABLE_ASYNC is defined.
The async member functions were always declared, despite
valud of NANODBC_DISABLE_ASYNC. In environment where async
features are not available, this leads to linker error
(e.g. undefined reference to async_connect).
This change avoids such late diagnostics.