feat: Add support for Win32 type _variant_t (#328)
Implement getters overloads for _variant_t

test: Add cases for _variant_t support, only for SQL Server, MySQL, PostgreSQL and SQLite.
test: Simplify usage of utility function get_binary_type_name
chore: Add missing #include <cstring> for std::memcpy

Initially, added MinGW support, but there have been hurdles
hard to overcome
- https://sourceforge.net/p/mingw-w64/bugs/940/
- _variant_t support there is either broken or it's entirely unclear
  how to configure the build and which library to link against
  to avoid linker errors like
     undefined reference to `_com_util::ConvertBSTRToString